from pymongo import MongoClient

# MongoDB connection setup
mongo_uri = "mongodb+srv://hfs:<hbghfs>@ag.ay8f5vq.mongodb.net/?retryWrites=true&w=majority&appName=ag"
client = MongoClient(mongo_uri)
db = client['attendance_db']
collection = db['student_emails']

# List of names and emails
data = [
    {"name": "Acevedo, Josue", "email": "jva5829@psu.edu"},
    {"name": "Ahmad, Mohammad", "email": "mohammad.ahmad@psu.edu"},
    {"name": "Ahmat, Aneesa", "email": "afa6049@psu.edu"},
    {"name": "Ahmed, Waqas", "email": "wja5138@psu.edu"},
    {"name": "Algarah, Reem Saud A", "email": "rsa5312@psu.edu"},
    {"name": "Altuwayjiri, Nouf", "email": "nqa5481@psu.edu"},
    {"name": "Amlani, Tanvi Rupeshkumar", "email": "tra5258@psu.edu"},
    {"name": "Anbalagan, Arthi", "email": "arthianbalagan@psu.edu"},
    {"name": "Awlia, Dana", "email": "dma5893@psu.edu"},
    {"name": "Bennett, Bryan R", "email": "brb5545@psu.edu"},
    {"name": "Bhatt, Mrudvi", "email": "mkb6611@psu.edu"},
    {"name": "Cantella, Giulia", "email": "gjc5610@psu.edu"},
    {"name": "Cao, Yunshu", "email": "ykc5481@psu.edu"},
    {"name": "Chorghe, Rohit", "email": "rpc5776@psu.edu"},
    {"name": "Choudhary, Prithvi", "email": "pfc5346@psu.edu"},
    {"name": "Chowdary, Bhuvanesh Sallagundla", "email": "bsc5486@psu.edu"},
    {"name": "Clement, Febin", "email": "fmc5271@psu.edu"},
    {"name": "Cruz-Yanes, Christian Gabriel", "email": "cpc6162@psu.edu"},
    {"name": "Deras, Angela Maya", "email": "amd7917@psu.edu"},
    {"name": "Dey, Kuber Oza", "email": "kod5261@psu.edu"},
    {"name": "Dural, Ata", "email": "axd5991@psu.edu"},
    {"name": "Fedorychev, Alexander", "email": "amf7257@psu.edu"},
    {"name": "Fields, Reginald", "email": "rxf5209@psu.edu"},
    {"name": "Gajipara, Rensi Nilesh", "email": "rng5152@psu.edu"},
    {"name": "Gandhi, Areet", "email": "apg6048@psu.edu"},
    {"name": "Garg, Anmol", "email": "abg6200@psu.edu"},
    {"name": "George, Peter Ulanga", "email": "pgu5002@psu.edu"},
    {"name": "Ghosh, Ritam", "email": "rpg5573@psu.edu"},
    {"name": "Goyal, Riya", "email": "rmg6205@psu.edu"},
    {"name": "Greenleaf, Kathleen", "email": "ksg5218@psu.edu"},
    {"name": "Gross, Abigail Elizabeth", "email": "apg5931@psu.edu"},
    {"name": "Gunturi, Sita Vaibhavi", "email": "gsv5053@psu.edu"},
    {"name": "Hamel, Jonathan Nicholas Yun", "email": "jnh5311@psu.edu"},
    {"name": "HFS Student Scheduler", "email": "scheduler@psu.edu"},
    {"name": "Hill, Destiny", "email": "dah6105@psu.edu"},
    {"name": "Jadhav, Apoorva Shashikant", "email": "asj5511@psu.edu"},
    {"name": "Johnson, Steven Tyler", "email": "stj5169@psu.edu"},
    {"name": "Joshi, Kathan Sanjay", "email": "ksj5289@psu.edu"},
    {"name": "KAMALESAN, AJITH KEVIN ANAND", "email": "axk6243@psu.edu"},
    {"name": "Khan, Sabiha", "email": "skk6224@psu.edu"},
    {"name": "Khatriya, Neha", "email": "nfk5315@psu.edu"},
    {"name": "Kim, Hyun Subb", "email": "hsk5172@psu.edu"},
    {"name": "KOLASANI, PAVANI", "email": "ppk5357@psu.edu"},
    {"name": "Koraganji, Vishnu", "email": "vfk5129@psu.edu"},
    {"name": "Lee, Jacq", "email": "jxl6891@psu.edu"},
    {"name": "Lobo, Nelson Divyam", "email": "ndl5213@psu.edu"},
    {"name": "Luo, Yanwen", "email": "ypl5780@psu.edu"},
    {"name": "Macaulay, Maeve Elizabeth", "email": "mem6957@psu.edu"},
    {"name": "Macklin, Jacob Alan", "email": "jam9242@psu.edu"},
    {"name": "Mahakal, Abhishek Mandar", "email": "amm10344@psu.edu"},
    {"name": "Malla, Sravani", "email": "sqm6704@psu.edu"},
    {"name": "Mallampalli, Sai Madhur", "email": "saimadhurmallampalli@psu.edu"},
    {"name": "Mason, Andrew Douglas", "email": "adm6264@psu.edu"},
    {"name": "McLaughlin, Patrick Henry", "email": "phm5149@psu.edu"},
    {"name": "Mehmood, Sana", "email": "szm6402@psu.edu"},
    {"name": "Mekala, Sumeet", "email": "sxm6596@psu.edu"},
    {"name": "Mercedes Abreu, Angel De Jesus", "email": "adm6017@psu.edu"},
    {"name": "Mikhailov, Max", "email": "msm6530@psu.edu"},
    {"name": "Mishra, Abhilasha", "email": "afm6697@psu.edu"},
    {"name": "Mohammed, Sameerah", "email": "sqm6271@psu.edu"},
    {"name": "Muessig, Tyler Jay", "email": "tpm5690@psu.edu"},
    {"name": "Naraveni, Geethika", "email": "gpn5134@psu.edu"},
    {"name": "Nguyen, An Thuy", "email": "atn5257@psu.edu"},
    {"name": "Nortey, Rebecca", "email": "rmn5441@psu.edu"},
    {"name": "Oberoi, Mannat Kaur", "email": "mqo5352@psu.edu"},
    {"name": "Owembabazi, Indira Yvette", "email": "iyo5032@psu.edu"},
    {"name": "Pasham, Mounika", "email": "mjp7163@psu.edu"},
    {"name": "Patel, Darsh Bharatkumar", "email": "dbp5588@psu.edu"},
    {"name": "Patel, Disha Mahendrabhai", "email": "dmp6528@psu.edu"},
    {"name": "Perez, Nyralee Isabel", "email": "nip5203@psu.edu"},
    {"name": "Ponnam, Varshith", "email": "vqp5208@psu.edu"},
    {"name": "Potnuri, Daanesh", "email": "dmp6538@psu.edu"},
    {"name": "Pradhan, Saatvik", "email": "szp6118@psu.edu"},
    {"name": "Rapaka, Ashna reddy", "email": "arr6117@psu.edu"},
    {"name": "Ravi, Daniel Sunil Kumar", "email": "dxr5576@psu.edu"},
    {"name": "Rayabharam, Siddharth", "email": "nqr5356@psu.edu"},
    {"name": "Regulapati, Adarsh", "email": "abr6174@psu.edu"},
    {"name": "Rivera, Ixzaira Jasmine", "email": "ijr5083@psu.edu"},
    {"name": "Rubio, Andres Eduardo", "email": "aer5788@psu.edu"},
    {"name": "Sadanala, Ganesh", "email": "gxs5493@psu.edu"},
    {"name": "Saini, Ishika", "email": "ims5409@psu.edu"},
    {"name": "Sapelli, Andrew", "email": "ajs9694@psu.edu"},
    {"name": "Shah, Aayushi Piyush", "email": "ams12225@psu.edu"},
    {"name": "Shah, Sneh", "email": "sbs7057@psu.edu"},
    {"name": "Sharma, Abhishek", "email": "axs7326@psu.edu"},
    {"name": "Sharma, Raghab", "email": "rps6236@psu.edu"},
    {"name": "Sheladia, Aditya Ketankumar", "email": "aps7194@psu.edu"},
    {"name": "Siddiqui, Muhammad Usman", "email": "mms8130@psu.edu"},
    {"name": "Singh Bist, Rakshit", "email": "rvs6202@psu.edu"},
    {"name": "Still, Joshua Tyler", "email": "jts6278@psu.edu"},
    {"name": "Syed, Rayyan", "email": "rvs6267@psu.edu"},
    {"name": "Tan, Jonathan", "email": "jzt5707@psu.edu"},
    {"name": "TARALLO, CLAUDIO", "email": "ckt5383@psu.edu"},
    {"name": "Thomas, Elena Thankam", "email": "ext5269@psu.edu"},
    {"name": "Troy, Harrison Michael", "email": "hmt5391@psu.edu"},
    {"name": "Tubo, Tiniira", "email": "txt5341@psu.edu"},
    {"name": "Varughese, Vivian Santosh", "email": "vxv5141@psu.edu"},
    {"name": "Wang, Yunxiang", "email": "yzw5705@psu.edu"},
    {"name": "Williams, Ta'Nya Abree", "email": "taw5867@psu.edu"},
    {"name": "Winter, Harry Ward", "email": "hww5203@psu.edu"},
    {"name": "Yawalkar, Manas Diwakar", "email": "mby5247@psu.edu"},
    {"name": "Zhao, Zihan", "email": "zxz5500@psu.edu"},
]

# Insert data into MongoDB
collection.insert_many(data)

print("Data inserted successfully!")
client.close()
